DROP TABLE IF EXISTS "user_groups";
--;;
DROP TABLE IF EXISTS "concerns";
--;;
DROP SEQUENCE IF EXISTS "concern_id_seq";
--;;
DROP TABLE IF EXISTS "kyoodos";
--;;
DROP SEQUENCE IF EXISTS "kyoodo_id_seq";
--;;
DROP TABLE IF EXISTS "groups";
--;;
DROP SEQUENCE IF EXISTS "group_id_seq";
--;;
DROP TABLE IF EXISTS "users";
--;;
DROP SEQUENCE IF EXISTS "user_id_seq";
