export const KYOODOS_GET = 'KYOODOS_GET'
export const KYOODOS_POST = 'KYOODOS_POST'

export const USER_GET = 'USER_GET'
export const GROUP_GET = 'GROUP_GET'

export const FETCH_API_REQUEST = 'FETCH_API_REQUEST'
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS'
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE'


